CREATE TABLE BOARD (
	BOARD_ID     NUMBER PRIMARY KEY,
	USER_ID      VARCHAR2(30),
	TITLE        VARCHAR2(100),
	BOARD_IMG    VARCHAR2(100),	-- 게시글의 메인 이미지 파일명
	CATEGORY     NUMBER(5) CHECK(CATEGORY IN (0, 1, 2, 3)), -- 0:전시회, 1:박람회, 2:버스킹, 3:연극/공연
	LOC          NUMBER(5) CHECK(LOC IN (0, 1, 2, 3, 4)),   -- 0: 서울, 1:경기/인천, 2:대전/충청/강원, 3:부산/대구/경상 4:광주/전라/제주
	HOST         VARCHAR2(100), -- 주최자
	ADDRESS      VARCHAR2(200), -- 상세 주소
	START_TIME   CHAR(5),		-- 00:00
	END_TIME     CHAR(5),
	START_DATE   CHAR(10),		-- YY-MM-DD
	END_DATE     CHAR(10),
	WRITE_DATE   DATE DEFAULT SYSDATE,
	CONTENT      VARCHAR2(4000),
	HEART_COUNT  NUMBER DEFAULT 0,		-- 관심수
	FOREIGN KEY(USER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE 
);


CREATE TABLE USER_HEART (
	USER_ID	  VARCHAR2(30) REFERENCES MEMBER(ID) ON DELETE CASCADE,
	BOARD_ID  NUMBER REFERENCES BOARD(BOARD_ID) ON DELETE CASCADE
);

