CREATE TABLE BOARD (
	BOARD_ID     NUMBER PRIMARY KEY,
	USER_ID      VARCHAR2(20),
	TITLE        VARCHAR2(100),
	MAIN_IMG     VARCHAR2(30),
	CATEGORY     NUMBER(5) CHECK(CATEGORY IN (0, 1, 2, 3)), -- 0:전시회, 1:박람회, 2:버스킹, 3:연극/공연
	LOC          NUMBER(5) CHECK(LOC IN (0, 1, 2, 3, 4)),   -- 0:서울, 1:경기/인천, 2:대전/충청/강원, 3:부산/대구/경상 4:광주/전라/제주
	HOST         VARCHAR2(100), -- 주최자
	ADDRESS      VARCHAR2(200), -- 상세 주소
	START_TIME   CHAR(5),  -- 00:00
	END_TIME     CHAR(5),
	START_DATE   CHAR(10), -- YY-MM-DD
	END_DATE     CHAR(10),
	WRITE_DATE   DATE DEFAULT SYSDATE,
	CONTENT      VARCHAR2(3000),
	FOREIGN KEY(USER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE 
);