CREATE TABLE MEMBER (
	ID		 	VARCHAR2(30) PRIMARY KEY,
	PASSWORD 	VARCHAR2(20),
	EMAIL 	 	VARCHAR2(20),
	NAME	 	VARCHAR2(10),
	PROFILE_IMG VARCHAR2(100),	-- 프로필 사진 파일명
	REG_DATE 	DATE DEFAULT SYSDATE
);

DROP TABLE MEMBER CASCADE CONSTRAINTS PURGE;